name: zoozy
description: "A new Flutter project."
publish_to: "none" # Bu satır uygulamanın pub.dev'e yanlışlıkla yüklenmesini engeller

version: 1.0.0+1

environment:
  # Dart SDK sürümü, güncel stabil sürümlere uyumluluk için güvenli bir aralıkta tutuldu.
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.9.1

  # Firebase Paketleri
  firebase_core: ^2.27.1
  flutter_facebook_auth: ^6.1.1
  firebase_auth: ^4.17.4

  # Diğer Paketler
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.4

  image_picker: ^1.1.2 # Resim seçmek için
  shared_preferences: ^2.2.2 # Veri kaydetmek için
  path_provider: ^2.1.2 # Resim yolunu kaydetmek için
  path: ^1.9.0 # Yol birleştirme işlemleri için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_1.png
    - assets/images/login_2.png
    - assets/images/login_3.png
    - assets/images/login_4.png
    - assets/images/forgot_password.png
    - assets/images/jobs.png
