name: zoozy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # Google Maps & Places (Dart 3 uyumlu)
  google_maps_flutter: ^2.3.0
  flutter_google_places_hoc081098: ^2.0.0
  google_maps_apis: ^4.0.0

  # Localization
  flutter_localizations:
    sdk: flutter

  # UI & Utils
  qr_flutter: ^4.1.0
  font_awesome_flutter: ^10.9.1
  intl_phone_field: ^3.1.0
  flutter_local_notifications: ^19.4.2
  mask_text_input_formatter: ^2.4.0
  audioplayers: ^6.5.1

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.1.0
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0

  path_provider: ^2.1.2
  path: ^1.9.0
  firebase_dynamic_links: ^6.1.10

  # Cupertino icons
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/caregiver1.png
    - assets/images/caregiver2.jpeg
    - assets/images/caregiver3.jpg
    - assets/images/forgot_password.png
    - assets/images/jobs.png
    - assets/images/login_1.png
    - assets/images/login_2.png
    - assets/images/login_3.png
    - assets/images/login_4.png
    - assets/images/pet1.jpeg
    - assets/images/pet2.jpeg
    - assets/images/pet3.jpg
    - assets/images/sitter_banner.jpg
