name: zoozy
description: "A new Flutter project."
publish_to: "none" # Bu satır uygulamanın pub.dev'e yanlışlıkla yüklenmesini engeller

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # iOS tarzı ikonlar
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets ekleme
  assets:
    - assets/images/login_1.png
    - assets/images/login_2.png
    - assets/images/login_3.png
    - assets/images/login_4.png
